---
- name: Configure Container Hosts
  hosts: "{{ apache_host }}"
  gather_facts: true
  become: true

  tasks:     
    - name: Retrieve Certs from Vault
      include_role:
        name: vault_read_certificates
      when: apache_install| default(false) |bool
    - name: Install Apache Reverse Proxy
      include_role:
        name: apache_reverse_proxy
      when: apache_install| default(false) |bool
