---
- name: Deploy Grafana Alloy for Log Collection
  hosts: alloy_hosts
  become: yes
  gather_facts: yes
  
  vars_files:
    - vars.yaml
  
  pre_tasks:
    - name: Ensure required directories exist
      file:
        path: "{{ item }}"
        state: directory
        owner: root
        group: root
        mode: '0755'
      loop:
        - "{{ alloy_path }}"
        - "{{ alloy_path }}/{{ alloy_config_dir }}"
        - "{{ alloy_workdir }}"
        - /root/bin
  
  tasks:
    - name: Set computed variables for Semaphore UI compatibility
      set_fact:
        hostname: "{{ inventory_hostname }}"
        loki_endpoint: "http://{{ loki_host }}:{{ loki_host_port }}/loki/api/v1/push"
        alloy_env_vars_computed: "{{ alloy_env_vars | combine({'HOSTNAME': inventory_hostname}) }}"
      tags:
        - always

    - name: Include download_alloy role
      include_role:
        name: download_alloy
      tags:
        - download
        - install
    
    - name: Include configure_alloy role  
      include_role:
        name: configure_alloy
      tags:
        - configure
        - config

    - name: Include networkmanager_dns role (if log_dns enabled and log_dns group defined)
      include_role:
        name: networkmanager_dns
      when: 
        - log_dns | default(false) | bool
        - inventory_hostname in groups['log_dns'] | default([])
      tags:
        - dns
        - networkmanager
  
  post_tasks:  
    - name: Wait for alloy service to be ready
      uri:
        url: "http://localhost:{{ alloy_metrics_port | default('12345') }}/ready"
        method: GET
        status_code: 200
      register: alloy_health
      until: alloy_health.status == 200
      retries: 30
      delay: 5
      ignore_errors: yes
    
    - name: Display alloy service status
      command: systemctl status alloy --no-pager -l
      register: alloy_status
      changed_when: false
    
    - name: Show alloy status
      debug:
        var: alloy_status.stdout_lines

  handlers:
    - name: reload systemd
      systemd:
        daemon_reload: yes
    
    - name: restart alloy
      systemd:
        name: alloy
        state: restarted
