- name: debug OPENSHIFT_CLUSTER_PROVISION_PARAMS
  debug:
    msg: "{{ OPENSHIFT_CLUSTER_PROVISION_PARAMS }}"

- name: Ensure LOCAL {{ CLUSTER_NAME }} Directory Exists
  ansible.builtin.file:
    path: "{{ OPENSHIFT_INSTALL_DIRECTORY }}"
    state: directory

- name: Generate cluster-config.yaml
  ansible.builtin.template:
    src: install-config.yaml.j2
    dest: "{{ OPENSHIFT_INSTALL_DIRECTORY }}/install-config.yaml"

