---
- name: Configure Virtualization Host
  hosts: "{{ virtualization_host }}"
  gather_facts: yes
  become: true

# Moved to awx project template
#  vars:
#    cockpit_packages:
#      - cockpit
#      - cockpit-bridge
#      - cockpit-system
#      - cockpit-networkmanager
#      - cockpit-packagekit
#      - cockpit-selinux
#      - cockpit-storaged
#      - cockpit-ws
#    extra_packages:
#      - inxi
#      - nano
#      - git
#    gpu_passthrough: true
#    kvm_packages:
#      - qemu-kvm
#      - libvirt
#      - virt-install
#    sanoid_repo_url: "https://github.com/jimsalterjrs/sanoid.git"
#    sanoid_clone_path: "/tmp/sanoid"
#    sanoid_install: true
#    shell_customizations: true
#    zfs_rpm_url: "https://zfsonlinux.org/epel/zfs-release-2-3.el9.noarch.rpm"
#    zfs_pool_name: "libvirt_nvmes"
#    zfs_pool_devices:
#      - mirror /dev/disk/by-id/nvme-Samsung_SSD_990_EVO_Plus_1TB_S7U5NJ0XA18459M /dev/disk/by-id/nvme-Samsung_SSD_990_EVO_Plus_1TB_S7U5NJ0XA18460W
#      - mirror /dev/disk/by-id/nvme-Samsung_SSD_990_EVO_Plus_1TB_S7U5NJ0XA18476F /dev/disk/by-id/nvme-Samsung_SSD_990_EVO_Plus_1TB_S7U5NJ0XA18491Y

    # Define the datasets you want, each with a specific mountpoint
#    zfs_base_mount_path: "/var/lib/libvirt_pools"
#    zfs_compression: true
#    zfs_datasets:
#      - wiki
#      - audio_video
#      - games
#      - infra
#      - containers
#      - base_images
#    zfs_dataset_creation: true
#    zfs_install: true
#    zfs_recordsize: "64K"
#    zpool_setup: true
  
  tasks:
    ###########################################################################
    # STEP 0: Install extra packages
    ###########################################################################
    - name: Install extra packages
      package:
        name: "{{ extra_packages }}"
        state: present

    - name: Enable Persistent Journal
      ansible.builtin.file:
        path: /var/log/journal
        state: directory

    - name: Customize Shell
      include_role:
        name: shell_customizations
      when: shell_customizations | default(false) |bool

    ###########################################################################
    # STEP 1: DETERMINE CPU VENDOR (AMD or Intel)
    ###########################################################################

    - name: Starting Nested Virt Checks
      include_role: 
        name: nested_virtualization


    ###########################################################################
    # STEP 2: INSTALL AND ENABLE KVM/LIBVIRTD + COCKPIT
    ###########################################################################
    - name: Install KVM packages (qemu-kvm, libvirt, virt-install)
      package:
        name: "{{ kvm_packages }}"
        state: present

    - name: Enable and start libvirtd
      service:
        name: libvirtd
        enabled: true
        state: started

    - name: Install Cockpit
      package:
        name: "{{ cockpit_packages }}"
        state: present

    - name: Enable and start Cockpit service
      service:
        name: cockpit
        enabled: true
        state: started

    - name: Starting ZFS Section
      include_role: 
        name: setup_zfs
      when: zfs_install | default(false) | bool


    ###########################################################################
    # STEP 6: Install Sanoid
    ###########################################################################

    - name: Evaluating Sanoid
      include_role:
        name: setup_sanoid
      when: sanoid_install| default(false) |bool

    - name: Enable GPU Passthrough
      include_role:
        name: gpu_passthrough
      when: gpu_passthrough | default(false) | bool

    - name: Verify GPU Passthrough
      include_role:
        name: gpu_passhtrough_verification
      when: gpu_passthrough | default(false) | bool
