    - name: Start ZFS Install
      include_tasks: install_zfs.yaml
      when: zfs_install | default(false) |bool

    - name: Zpool Setup
      include_tasks: create_zpool.yaml
      when: zpool_setup |default(false) | bool

    - name: ZFS Dataset Creation
      include_tasks: create_dataset.yaml
      loop: "{{ zfs_datasets }}"
      loop_control:
        loop_var: dataset_item
      when: zfs_dataset_creation |default(false) |bool
