---
- name: Check if qcow2 disk image already exists (fast)
  ansible.builtin.shell: |
    test -f "{{ vm_libvirt_disk_path }}/{{ vm_name }}.{{ CLUSTER_NAME }}.{{ BASE_DOMAIN }}.qcow2" && echo "true" || echo "false"
  register: disk_image_check
  changed_when: false

- name: Set disk image exists fact
  ansible.builtin.set_fact:
    disk_image_exists: "{{ disk_image_check.stdout | bool }}"

- name: Check if VM is already defined
  community.libvirt.virt:
    command: status
    name: "{{ vm_name }}.{{ CLUSTER_NAME }}.{{ BASE_DOMAIN }}"
  register: vm_status
  ignore_errors: true

- name: Create VM XML definition
  ansible.builtin.template:
    src: vm_template.xml.j2
    dest: "/tmp/{{ vm_name }}.xml"
  when: vm_status is failed

- name: Read VM XML definition
  ansible.builtin.slurp:
    src: "/tmp/{{ vm_name }}.xml"
  register: vm_xml_content
  when: vm_status is failed

- name: Define VM
  community.libvirt.virt:
    command: define
    xml: "{{ vm_xml_content.content | b64decode }}"
    uri: qemu:///system
  when: vm_status is failed

- name: Display disk image status
  ansible.builtin.debug:
    msg: >
      {{ node_type | title }} node disk image {{ vm_libvirt_disk_path }}/{{ vm_name }}.{{ CLUSTER_NAME }}.{{ BASE_DOMAIN }}.qcow2 
      {% if disk_image_exists %}already exists, skipping creation{% else %}does not exist, will create{% endif %}
      (using {{ node_type }} storage pool: {{ vm_libvirt_pool_name }})

- name: Create the disk image file ({{ vm_libvirt_disk_size }}GB) for {{ node_type }} node
  ansible.builtin.command: >
    qemu-img create -f qcow2 
    {{ vm_libvirt_disk_path }}/{{ vm_name }}.{{ CLUSTER_NAME }}.{{ BASE_DOMAIN }}.qcow2 
    {{ vm_libvirt_disk_size }}G
  when: not disk_image_exists
  register: qemu_img_result

- name: Set proper permissions on disk image
  ansible.builtin.file:
    path: "{{ vm_libvirt_disk_path }}/{{ vm_name }}.{{ CLUSTER_NAME }}.{{ BASE_DOMAIN }}.qcow2"
    owner: qemu
    group: qemu
    mode: '0660'
  # Always ensure correct permissions, whether file is new or existing

- name: Refresh the storage pool
  community.libvirt.virt_pool:
    command: refresh
    name: "{{ vm_libvirt_pool_name }}"
  when: not disk_image_exists

- name: Verify VM creation completed successfully
  ansible.builtin.debug:
    msg: >
      VM {{ vm_name }}.{{ CLUSTER_NAME }}.{{ BASE_DOMAIN }} 
      {% if vm_status is failed %}has been created and defined successfully{% else %}was already defined, skipped creation{% endif %}.
