---
- name: Configure Container Hosts
  hosts: virtualization
  gather_facts: yes
  become: true
  # uncomment below for local playbook
  # vars:
  #   apache_install: true
  #   docker_install: true
  #   apache_packages:
  #     - httpd
  #     - mod_ssl
  #   nvidia_install: true
  #   vhosts:
  #     - name: example.com
  #       cert_file_location: /path/to/example.com.crt
  #       cert_key_file_location: /path/to/example.com.key
  #       app_port: 8080

  tasks:
    - name: Install Docker
      include_role:
        name: docker_host
      when: docker_install| default(false) |bool
    
    - name: Install NVIDIA drivers
      include_role:
        name: nvidia_drivers
      when: nvidia_install| default(false) |bool
    
    # Use the improved roles from rhel_apache_reverse_proxy
    - name: Retrieve Certs from Vault
      include_role:
        name: vault_read_certificates
        tasks_from: "{{ playbook_dir }}/../rhel_apache_reverse_proxy/roles/vault_read_certificates"
      when: apache_install| default(false) |bool

    - name: Install Apache Reverse Proxy
      include_role:
        name: apache_reverse_proxy
        tasks_from: "{{ playbook_dir }}/../rhel_apache_reverse_proxy/roles/apache_reverse_proxy"
      when: apache_install| default(false) |bool