- name: Update pacman.conf
  blockinfile:
    path: /etc/pacman.conf
    block: |
      [endeavouros]
      SigLevel = PackageRequired
      Include = /etc/pacman.d/endeavouros-mirrorlist
  when:
    - enable_endeavour | bool
    
- name: Include Endeavour OS Repo
  include_tasks: endeavour_repo.yaml

- name: Install Cinnamon packages
  become: yes
  become_user: "{{ username }}"
  kewlfft.aur.aur:
    use: yay
    name:
      - cinnamon
      - lightdm
      - lightdm-slick-greeter
      - arc-gtk-theme-eos
      - eos-lightdm-slick-theme
      - eos-qogir-icons
      - eos-settings-cinnamon
      - cinnamon-sounds
    state: present

- name: Enable systemd services
  systemd:
    name: "{{ item }}"
    enabled: yes
  loop:
    - lightdm

- name: Create lightdm service directory and configuration files
  block:
    - name: Ensure lightdm service directory exists
      ansible.builtin.file:
        path: /etc/systemd/system/lightdm.service.d
        state: directory
        mode: '0755'

    - name: Create delay.conf file
      ansible.builtin.copy:
        dest: /etc/systemd/system/lightdm.service.d/delay.conf
        content: |
          [Service]
          ExecStartPre=/bin/sleep 5
        mode: '0644'

    - name: Create override.conf file
      ansible.builtin.copy:
        dest: /etc/systemd/system/lightdm.service.d/override.conf
        content: |
          [Unit]
          After=multi-user.target
        mode: '0644'

- name: Configure Autostart Applications
  block:
    - name: fetch autostart applications
      ansible.builtin.get_url:
        url: http://{{ remote_server }}/autostart.tar.gz
        dest: /home/{{ username }}/.config
        mode: '0664'

    - name: extract autostart tarball
      ansible.builtin.unarchive:
        src: /home/{{ username }}/.config/autostart.tar.gz
        dest: /home/{{ username }}/.config/
        owner: "{{ username }}"
  when:
    - auto_start_app | bool
