- name: Install Deepin packages
  become: yes
  become_user: "{{ username }}"
  kewlfft.aur.aur:
    use: yay
    name:
      - deepin
      - deepin-kwin
      - deepin-album
      - deepin-calculator
      - deepin-camera
      - deepin-clipboard
      - deepin-community-wallpapers
      - deepin-compressor
      - deepin-device-formatter
      - deepin-editor
      - deepin-font-manager
      - deepin-grand-search
      - deepin-movie
      - deepin-music
      - deepin-picker
      - deepin-printer
      - deepin-screen-recorder
      - deepin-screensaver-pp
    state: present

- name: Enable systemd services
  systemd:
    name: "{{ item }}"
    enabled: yes
  loop:
    - lightdm

- name: Create lightdm service directory and configuration files
  block:
    - name: Ensure lightdm service directory exists
      ansible.builtin.file:
        path: /etc/systemd/system/lightdm.service.d
        state: directory
        mode: '0755'

    - name: Create delay.conf file
      ansible.builtin.copy:
        dest: /etc/systemd/system/lightdm.service.d/delay.conf
        content: |
          [Service]
          ExecStartPre=/bin/sleep 2
        mode: '0644'

    - name: Create override.conf file
      ansible.builtin.copy:
        dest: /etc/systemd/system/lightdm.service.d/override.conf
        content: |
          [Unit]
          After=multi-user.target
        mode: '0644'

- name: Configure Autostart Applications
  block:
    - name: fetch autostart applications
      ansible.builtin.get_url:
        url: http://{{ remote_server }}/autostart.tar.gz
        dest: /home/{{ username }}/.config
        mode: '0664'

    - name: extract autostart tarball
      ansible.builtin.unarchive:
        src: /home/{{ username }}/.config/autostart.tar.gz
        dest: /home/{{ username }}/.config/
        owner: "{{ username }}"
  when:
    - auto_start_app | bool


