---
- name: Create DNS for Bootstrap
  pfsensible.core.pfsense_dns_resolver:
    state: present
    hosts:
      - host: "bootstrap"
        domain: "{{ CLUSTER_NAME }}.{{ BASE_DOMAIN }}"
        ip: "{{ BOOTSTRAP_STATIC_IP }}"
        descr: "OCP bootstrap node"

- name: Create DNS entry for OCP hosts
  pfsensible.core.pfsense_dns_resolver:
    state: present
    hosts:
      - host: "{{ item.openshift_node_fqdn }}"
        domain: "{{ CLUSTER_NAME }}.{{ BASE_DOMAIN }}"
        ip: "{{ item.openshift_node_machine_ip_address }}"
        descr: "OCP {{ 'master' if item.openshift_control_node else 'worker' }}"
  loop: "{{ openshift_cluster_provision_params }}"

- name: Add zone redirects for the api & apps
  pfsensible.core.pfsense_dns_resolver:
    state: present
    custom_options: |
      local-zone: "api.{{ CLUSTER_NAME }}.{{ BASE_DOMAIN }}" redirect
      local-data: "api.{{ CLUSTER_NAME }}.{{ BASE_DOMAIN }} 86400 IN A {{ API_VIP }}"
      local-zone: "apps.{{ CLUSTER_NAME }}.{{ BASE_DOMAIN }}" redirect
      local-data: "apps.{{ CLUSTER_NAME }}.{{ BASE_DOMAIN }} 86400 IN A {{ APP_VIP }}"
