---
- name: Store files in HashiCorp Vault
  community.hashi_vault.vault_write:
    auth_method: "approle"
    url: "{{ ansible_hashi_vault_url }}"
    role_id: "{{ ansible_hashi_vault_role_id }}"
    secret_id: "{{ ansible_hashi_vault_secret_id }}"
    path: "{{ vault_path }}"
    data:
      data:
        "{{ file_name }}": "{{ lookup('file', full_path_to_file ) | b64encode }}"
