---
- name: Slurp install-config.yaml from remote host
  slurp:
    src: "{{ full_path_to_file }}"
  register: slurped_install_config

- name: Set vault_dict fact for Vault
  set_fact:
    vault_dict:
      - key: "{{ vault_secret_key_name }}"
        value: "{{ slurped_install_config.content }}"

- ansible.builtin.debug:
    var: vault_dict

- name: Store files in HashiCorp Vault
  community.hashi_vault.vault_write:
    auth_method: "approle"
    url: "{{ HASHI_VAULT_URL }}"
    role_id: "{{ HASHI_VAULT_ROLE_ID }}"
    secret_id: "{{ HASHI_VAULT_SECRET_ID }}"
    path: "{{ HASHI_VAULT_PATH }}"
    data:
      data:
         "{{ vault_dict | items2dict }}"
