---
- name: create the data dict for Vault
  ansible.builtin.set_fact:
    vault_dict:
      - key: "{{ file_name }}"
        value: "{{ lookup('file', full_path_to_file ) | b64encode }}"

- name: Store files in HashiCorp Vault
  community.hashi_vault.vault_write:
    auth_method: "approle"
    url: "{{ HASHI_VAULT_URL }}"
    role_id: "{{ HASHI_VAULT_ROLE_ID }}"
    secret_id: "{{ HASHI_VAULT_SECRET_ID }}"
    path: "{{ HASHI_VAULT_PATH }}"
    data:
      data:
         "{{ vault_dict | items2dict }}"
