---
- block:
    - name: Ensure remote certificate directory exists
      file:
        path: "/etc/letsencrypt/live/{{ base_domain }}"
        state: directory
        mode: '0750'
        owner: root
        group: root

    - name: Copy certificates to remote host
      copy:
        src: "{{ cert_dir }}/{{ item }}"
        dest: "/etc/letsencrypt/live/{{ base_domain }}/{{ item }}"
        mode: '0640'
        owner: root
        group: root
      loop:
        - cert.pem
        - chain.pem
        - fullchain.pem
        - privkey.pem
  when: renew_certificate
