- name: Install Cinnamon packages
  become: yes
  become_user: "{{ username }}"
  kewlfft.aur.aur:
    use: yay
    name:
      - cinnamon
      - lightdm
      - lightdm-slick-greeter
      - arc-gtk-theme-eos
      - eos-lightdm-slick-theme
      - eos-qogir-icons
      - eos-settings-cinnamon
      - cinnamon-sounds
    state: present

- name: Enable systemd services
  systemd:
    name: "{{ item }}"
    enabled: yes
  loop:
    - lightdm
