---
- name: Wrapper
  hosts: localhost
  become: true 
  tasks:
    - include_tasks: install-zfs.yaml
      vars:
        username: ''
        user_password: ''
        desktop: true
        desktop_name: cinnamon
        nvidia_open: true
        nvidia_dkms: false
        nvidia_lts: false
        flatpak: true
        network_pacman_cache: true
        nfs_path: '192.168.1.1:/storage/backups/pacman_cache'
        enable_endeavour: true
