---
- name: Wrapper
  hosts: localhost
  become: true
  tasks:
    - include_tasks: system-setup.yaml
      vars:
        username: ''
        user_password: ''
        desktop: true
        desktop_name: cinnamon
        nvidia_open: false
        nvidia_dkms: false
        nvidia_lts: true
        flatpak: true
        network_pacman_cache: true
        remote_server: 192.168.1.1
        nfs_path: '{{ remote_server }}:/storage/backups/pacman_cache'
        enable_endeavour: true
        update_fstab: true
        device_name: "/dev/xxx"
        sudoers_suspend_no_passwd: true
        custom_firefox_icon: true
        restore_firefox_backup: true
        restore_user_cryptography: true
        auto_start_app: true
