amdgpu_fix: false
auto_start_app: false
boot_mode: "bios" # or "uefi"
boot_partition: ""
custom_firefox_icon: false
desktop_name: cinnamon
desktop: true
device_name: /dev/xxx 
efi_partition: "" # this is initiated blank
enable_endeavour: true
faillock_increase: true
faillock_retries: 6
filesystem_type: "xfs"
flatpak: false
fstab_directories: []
fstab_entries: []
gaming_platform: false
install_rustdesk: false
journald_on_zfs: false
libvirt: false
luks_passphrase: "" # FILL ME
luks_volume_name: "cryptroot"
network_pacman_cache: true
nfs_path: '{{ remote_server }}:/var/cache/pacman/pkg'
network_pacman_cache: true
nvidia_dkms: false
nvidia_lts: false
nvidia_open: false
old_pacman_version: false
remote_server: 192.168.8.95
restore_firefox_backup: false
restore_user_cryptography: false
sudoers_suspend_no_passwd: false
touchpad_fix: false
update_fstab: false
use_archzfs_repo: false
use_custom_repo: false
use_luks: false
use_zfs: false
username: 'stratus' # FILL ME
user_password: '' # FILL ME
zfs_partition: "" # this is initiated blank
zfs_partition_names:
    - mountpoint: "/"
      name: "zroot/ROOT/default"
      canmount: "noauto"
    - mountpoint: "/home"
      name: "zroot/data/home"
    - mountpoint: "none"
      name: "zroot/ROOT"
    - mountpoint: "none"
      name: "zroot/data"  
zfs_root_dataset: "zroot"
