auto_start_app: true
custom_firefox_icon: true
desktop_name: cinnamon
desktop: true
device_name: /dev/xxx 
efi_partition: "" # this is initiated blank
enable_endeavour: true
flatpak: true
journald_on_zfs: true
libvirt: true
network_pacman_cache: true
nfs_path: '{{ remote_server }}:/storage/backups/pacman_cache'
network_pacman_cache: true
nvidia_dkms: false
nvidia_lts: true
nvidia_open: false
remote_server: 192.168.1.1
restore_firefox_backup: true
restore_user_cryptography: true
sudoers_suspend_no_passwd: true
update_fstab: true
username: '' # FILL ME
user_password: '' # FILL ME
zfs_partition: "" # this is initiated blank
