- name: register control plane info
  community.libvirt.virt:
    command: get_interfaces
    name: "{{ vm_name }}.{{ CLUSTER_NAME }}.{{ BASE_DOMAIN }}"
  register: control_plane_info
  loop: "{{ CONTROL_PLANE_NAMES }}"
  loop_control:
    loop_var: vm_name

- name: register worker plane info
  community.libvirt.virt:
    command: get_interfaces
    name: "{{ vm_name }}.{{ CLUSTER_NAME }}.{{ BASE_DOMAIN }}"
  register: worker_info
  loop: "{{ WORKER_NAMES }}"
  loop_control:
    loop_var: vm_name
  when: 
    - WORKER_NAMES is defined
    - NUMBER_OF_WORKER_VMS !=0

- name: show variable
  debug:
    msg: "{{ OPENSHIFT_CLUSTER_PROVISION_PARAMS }}"
  when: DEBUG is defined and DEBUG | bool

- name: Create dictionary for control plane MAC addresses keyed by FQDN
  ansible.builtin.set_fact:
    control_plane_macs: >-
      {{
        dict(
          CONTROL_PLANE_NAMES
          | map('regex_replace', '^(.*)$', '\1.' ~ CLUSTER_NAME ~ '.' ~ BASE_DOMAIN)
          | zip(control_plane_info.results | map(attribute='network_interfaces'))
        )
      }}

- name: Debug control plane macs
  debug:
    msg: "{{ control_plane_macs }}"
  when: 
    - control_plane_macs is defined
    - DEBUG is defined and DEBUG | bool

- name: Create dictionary for worker MAC addresses keyed by FQDN
  ansible.builtin.set_fact:
    worker_macs: >-
      {{
        dict(
          WORKER_NAMES
          | map('regex_replace', '^(.*)$', '\1.' ~ CLUSTER_NAME ~ '.' ~ BASE_DOMAIN)
          | zip(worker_info.results | map(attribute='network_interfaces'))
        )
      }}
  when: 
    - WORKER_NAMES is defined
    - NUMBER_OF_WORKER_VMS !=0

- name: debug worker macs
  debug:
    msg: "{{ worker_macs }}"
  when: 
    - WORKER_NAMES is defined
    - NUMBER_OF_WORKER_VMS !=0
    - worker_macs is defined
    - DEBUG is defined and DEBUG | bool  

- name: Build updated list
  ansible.builtin.set_fact:
    updated_list: "{{ updated_list|default([]) + [ merged_item ] }}"
  loop: "{{ OPENSHIFT_CLUSTER_PROVISION_PARAMS }}"
  loop_control:
    label: "{{ item.openshift_node_fqdn }}"
  vars:
    merged_item: >-
      {{
        item | combine({
          'openshift_node_mac_address':
            (
              control_plane_macs[item.openshift_node_fqdn][control_plane_macs[item.openshift_node_fqdn].keys()|list|first].mac
              if item.openshift_control_node
              else (
                worker_macs[item.openshift_node_fqdn][worker_macs[item.openshift_node_fqdn].keys()|list|first].mac
                if (WORKER_NAMES is defined and NUMBER_OF_WORKER_VMS != 0 and worker_macs is defined)
                else omit
              )
            )
        })
      }}
  when: >-
    item.openshift_control_node or
    (WORKER_NAMES is defined and NUMBER_OF_WORKER_VMS != 0)



- name: Update the original data structure
  ansible.builtin.set_fact:
    OPENSHIFT_CLUSTER_PROVISION_PARAMS: "{{ updated_list }}"

# added by Cursor using Claude 4 Sonnet
- name: Display MAC address extraction summary
  debug:
    msg: >
      Successfully extracted MAC addresses for {{ updated_list | length }} nodes:
      Control Plane: {{ control_plane_macs.keys() | list | length if control_plane_macs is defined else 0 }} nodes,
      Workers: {{ worker_macs.keys() | list | length if worker_macs is defined else 0 }} nodes
  when: DEBUG is defined and DEBUG | bool
