---
- name: Deploy Node Exporter and Register with Prometheus
  hosts: "{{ node_exporter_host }}"
  become: true
  vars_files:
    - ../prometheus_server/vars.yaml
  tasks:
    # Install Node Exporter (conditionally)
    - name: Include node_exporter role
      include_role:
        name: node_exporter
      when: not skip_node_exporter_install | default(false) | bool

    # Display deployment summary
    - name: Display deployment summary
      debug:
        msg: |
          Node Exporter Deployment Summary:
          ===============================
          Total hosts processed: {{ ansible_play_hosts | length }}
          Successfully processed: {{ ansible_play_hosts | length }} hosts
          
          Processed hosts:
          {% for host in ansible_play_hosts %}
          - {{ host }}
          {% endfor %}
          
          Skip installation: {{ skip_node_exporter_install | default(false) }}
          Auto-register with Prometheus: {{ auto_register_with_prometheus | default(true) }}
          Prometheus host: {{ prometheus_host | default('prometheus_servers') }}
          Prometheus port: {{ prometheus_host_port | default(9191) }}
      run_once: true

    - name: Final deployment status (before registration)
      debug:
        msg: |
          =======================================================
          NODE EXPORTER DEPLOYMENT COMPLETE
          =======================================================
          
          ✓ Node exporters {{ 'configured' if skip_node_exporter_install | default(false) else 'deployed' }}: {{ ansible_play_hosts | length }} hosts
          ✓ Prometheus registration: {{ 'AUTOMATIC (calling API update)' if auto_register_with_prometheus | default(true) else 'MANUAL' }}
          
          {% if not (auto_register_with_prometheus | default(true)) %}
          To register manually, run:
          ansible-playbook prometheus_exporter/deploy_and_register_exporter.yaml \
            -e "hosts_to_add={{ ansible_play_hosts | join(',') }}" \
            -e "skip_node_exporter_install=true"
          {% endif %}
      run_once: true

    # Update Prometheus targets (runs on prometheus host)  
    - block:
        - name: Include prometheus_targets role
          include_role:
            name: prometheus_targets
          vars:
            hosts_to_add: "{{ ansible_play_hosts }}"
            hosts_to_remove: []
            backup_prometheus_config: true
            validate_prometheus_config: true
      delegate_to: "{{ prometheus_host | default('prometheus_servers') }}"
      become: true
      run_once: true
      when: 
        - auto_register_with_prometheus | default(true) | bool
        - ansible_play_hosts | length > 0

