---
# API-based Prometheus Target Management
# This playbook reads the current Prometheus configuration via API and intelligently updates targets

- name: Update Prometheus Targets via API
  hosts: "{{ prometheus_host | default('prometheus_servers') }}"
  become: true
  vars_files:
    - ../prometheus_server/vars.yaml
  vars:
    # Node exporter settings
    node_exporter_port: "{{ node_exporter_port | default('9100') }}"
    
    # Hosts to add to monitoring (from current deployment or manual specification)
    hosts_to_add: "{{ hosts_to_add | default([]) }}"
    hosts_to_remove: "{{ hosts_to_remove | default([]) }}"
    
    # Prometheus API settings - construct URL based on current host
    prometheus_host_port: "{{ prometheus_host_port | default(9191) }}"
    
    # Configuration options
    backup_prometheus_config: "{{ backup_prometheus_config | default(true) }}"
    validate_prometheus_config: "{{ validate_prometheus_config | default(true) }}"

  roles:
    - prometheus_targets